# Generated by Django 3.0.6 on 2020-05-25 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, default='default.jpg', upload_to='profile_pics')),
                ('cover_pic', models.ImageField(blank=True, default='coverdefault.jpg', upload_to='cover_photos')),
                ('fullname', models.CharField(blank=True, max_length=150)),
                ('position', models.CharField(blank=True, default='An employee of Orgeon of stars', max_length=100)),
                ('bio', models.CharField(blank=True, default='Just a music lover', max_length=200)),
                ('verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
