# Generated by Django 3.0.6 on 2020-05-25 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(choices=[('GradeSchool', 'GradeSchool'), ('Preschool', 'Preschool'), ('Kindergarten', 'Kindergarten')], max_length=20)),
                ('fullname', models.CharField(blank=True, max_length=150)),
                ('age', models.IntegerField(blank=True, default=10)),
                ('grade', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], help_text='Please leave this field blank when your school is not GradeSchool,thank you', max_length=3)),
                ('photo', models.ImageField(blank=True, default='kid.jpg', upload_to='kids_grade_school_photos')),
                ('name_of_parent_or_guardian', models.CharField(blank=True, max_length=150)),
                ('contact_number', models.CharField(blank=True, max_length=30)),
                ('verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
