# Generated by Django 3.0.6 on 2020-05-25 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summerschool', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyStudent',
            new_name='Student',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='user_email',
            new_name='student_email',
        ),
    ]
