# Generated by Django 3.0.6 on 2020-05-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_clientinfoprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinfoprogress',
            name='gender',
            field=models.CharField(default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='clientinfoprogress',
            name='next_of_kin',
            field=models.CharField(max_length=50),
        ),
    ]
