# Generated by Django 3.0.3 on 2020-02-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200218_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instantmessage',
            name='message_poster',
        ),
        migrations.AlterField(
            model_name='instantmessage',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
