# Generated by Django 3.0.6 on 2020-05-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200508_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfoprogress',
            name='client_image',
            field=models.ImageField(blank=True, default='client.jpg', upload_to='client_images'),
        ),
        migrations.AlterField(
            model_name='clientinfoprogress',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='Male', max_length=10),
        ),
    ]
