# Generated by Django 3.0.3 on 2020-02-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200224_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeestory',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
