# Generated by Django 3.0.6 on 2020-05-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200517_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinfoprogress',
            name='age',
            field=models.IntegerField(blank=True, default=10),
        ),
    ]
