# Generated by Django 3.0.3 on 2020-04-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200419_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='chatters',
            field=models.CharField(default='somechats', max_length=1000),
        ),
    ]
