# Generated by Django 3.0.3 on 2020-02-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200224_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeestory',
            name='feeling_now',
            field=models.CharField(blank=True, choices=[('Happy', 'Happy'), ('Sad', 'Sad'), ('Confued', 'Confued'), ('Smiling', 'Smiling'), ('Crying', 'Crying'), ('Winki', 'Winki'), ('Chilling', 'Chilling')], max_length=20),
        ),
    ]
