# Generated by Django 3.0.3 on 2020-04-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_message_chatters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chatters',
        ),
        migrations.AlterField(
            model_name='message',
            name='date_sent',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
