# Generated by Django 3.0.3 on 2020-02-26 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_postreplies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeestory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='postreplies',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='postreplies',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='reply',
        ),
        migrations.DeleteModel(
            name='EmployeeComments',
        ),
        migrations.DeleteModel(
            name='EmployeeStory',
        ),
        migrations.DeleteModel(
            name='PostReplies',
        ),
    ]
