# Generated by Django 3.0.3 on 2020-02-26 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200226_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comment_content',
            new_name='reply',
        ),
    ]
