# Generated by Django 3.0.3 on 2020-02-26 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200226_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsupdate',
            old_name='news',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='newsupdate',
            name='email',
        ),
    ]
