# Generated by Django 3.0.3 on 2020-02-29 19:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0019_auto_20200229_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='has_read',
            field=models.ManyToManyField(blank=True, related_name='has_read_report', to=settings.AUTH_USER_MODEL),
        ),
    ]
