# Generated by Django 3.0.3 on 2020-02-29 21:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0020_report_has_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='has_read',
            field=models.ManyToManyField(blank=True, related_name='has_read_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
