# Generated by Django 3.0.3 on 2020-03-01 13:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20200301_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='date',
        ),
        migrations.AddField(
            model_name='events',
            name='date_of_event',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
