# Generated by Django 3.0.3 on 2020-03-06 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20200305_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='photo',
        ),
    ]
