# Generated by Django 3.0.3 on 2020-03-10 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_online_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logincode',
            name='login_code',
        ),
    ]
