# Generated by Django 3.0.3 on 2020-03-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_remove_logincode_login_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='reply',
            field=models.TextField(blank=True),
        ),
    ]
