# Generated by Django 3.0.3 on 2020-03-14 19:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20200312_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstantReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_content', models.TextField(max_length=200)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('imessage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_to_message', to='blog.InstantMessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.InstantMessage')),
            ],
        ),
    ]
