# Generated by Django 3.0.3 on 2020-03-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20200314_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='instantreply',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
